
import { Product, Category } from './types';

export const CATEGORIES = [
  { id: 'all', name: 'All Items', icon: '🛒' },
  { id: 'vegetables', name: 'Vegetables', icon: '🥦' },
  { id: 'fruits', name: 'Fruits', icon: '🍎' },
  { id: 'leafy', name: 'Leafy Greens', icon: '🥬' },
  { id: 'exotics', name: 'Exotics', icon: '🍄' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Organic Cherry Tomatoes',
    category: 'vegetables',
    price: 89,
    originalPrice: 120,
    unit: '250g',
    image: 'https://picsum.photos/seed/tomato/400/300',
    description: 'Farm-fresh organic cherry tomatoes bursting with flavor.',
    isOrganic: true,
    stock: 50,
    deliveryTime: '12 mins'
  },
  {
    id: '2',
    name: 'Fresh Spinach',
    category: 'leafy',
    price: 45,
    originalPrice: 60,
    unit: '1 bunch',
    image: 'https://picsum.photos/seed/spinach/400/300',
    description: 'Crispy, vibrant green spinach leaves, pesticide-free.',
    isOrganic: true,
    stock: 20,
    deliveryTime: '10 mins'
  },
  {
    id: '3',
    name: 'Hass Avocados',
    category: 'exotics',
    price: 299,
    originalPrice: 350,
    unit: '1 pc',
    image: 'https://picsum.photos/seed/avocado/400/300',
    description: 'Creamy organic avocados imported from best farms.',
    isOrganic: true,
    stock: 15,
    deliveryTime: '15 mins'
  },
  {
    id: '4',
    name: 'Organic Carrots',
    category: 'vegetables',
    price: 55,
    originalPrice: 75,
    unit: '500g',
    image: 'https://picsum.photos/seed/carrot/400/300',
    description: 'Crunchy and sweet organic carrots.',
    isOrganic: true,
    stock: 40,
    deliveryTime: '11 mins'
  },
  {
    id: '5',
    name: 'Gala Apples',
    category: 'fruits',
    price: 180,
    originalPrice: 220,
    unit: '1kg',
    image: 'https://picsum.photos/seed/apple/400/300',
    description: 'Crisp organic apples, perfect for snacking.',
    isOrganic: true,
    stock: 30,
    deliveryTime: '14 mins'
  },
  {
    id: '6',
    name: 'Oyster Mushrooms',
    category: 'exotics',
    price: 120,
    originalPrice: 150,
    unit: '200g',
    image: 'https://picsum.photos/seed/mushroom/400/300',
    description: 'Grown on organic substrate, premium quality.',
    isOrganic: true,
    stock: 12,
    deliveryTime: '18 mins'
  },
  {
    id: '7',
    name: 'Organic Broccoli',
    category: 'vegetables',
    price: 95,
    unit: '1 pc',
    image: 'https://picsum.photos/seed/broccoli/400/300',
    description: 'Dense, nutritious organic broccoli.',
    isOrganic: true,
    stock: 25,
    deliveryTime: '12 mins'
  },
  {
    id: '8',
    name: 'Baby Kale',
    category: 'leafy',
    price: 70,
    unit: '100g',
    image: 'https://picsum.photos/seed/kale/400/300',
    description: 'Tender baby kale leaves for salads.',
    isOrganic: true,
    stock: 15,
    deliveryTime: '13 mins'
  },
  {
    id: '9',
    name: 'Organic Bananas',
    category: 'fruits',
    price: 60,
    originalPrice: 80,
    unit: '500g',
    image: 'https://picsum.photos/seed/banana/400/300',
    description: 'Naturally ripened organic bananas from South India.',
    isOrganic: true,
    stock: 100,
    deliveryTime: '9 mins'
  },
  {
    id: '10',
    name: 'Red Bell Pepper',
    category: 'vegetables',
    price: 110,
    originalPrice: 140,
    unit: '250g',
    image: 'https://picsum.photos/seed/pepper/400/300',
    description: 'Vibrant and crunchy organic red bell peppers.',
    isOrganic: true,
    stock: 20,
    deliveryTime: '15 mins'
  },
  {
    id: '11',
    name: 'Fresh Coriander',
    category: 'leafy',
    price: 15,
    unit: '1 bunch',
    image: 'https://picsum.photos/seed/coriander/400/300',
    description: 'Aromatic and fresh organic coriander leaves.',
    isOrganic: true,
    stock: 50,
    deliveryTime: '8 mins'
  },
  {
    id: '12',
    name: 'Shiitake Mushrooms',
    category: 'exotics',
    price: 250,
    originalPrice: 300,
    unit: '200g',
    image: 'https://picsum.photos/seed/shiitake/400/300',
    description: 'Meaty and flavorful organic shiitake mushrooms.',
    isOrganic: true,
    stock: 10,
    deliveryTime: '20 mins'
  },
  {
    id: '13',
    name: 'Organic Garlic',
    category: 'vegetables',
    price: 40,
    unit: '100g',
    image: 'https://picsum.photos/seed/garlic/400/300',
    description: 'Strong and pungent organic garlic bulbs.',
    isOrganic: true,
    stock: 60,
    deliveryTime: '10 mins'
  },
  {
    id: '14',
    name: 'Blueberries',
    category: 'fruits',
    price: 450,
    originalPrice: 550,
    unit: '125g',
    image: 'https://picsum.photos/seed/blueberries/400/300',
    description: 'Antioxidant-rich organic blueberries.',
    isOrganic: true,
    stock: 8,
    deliveryTime: '18 mins'
  },
  {
    id: '15',
    name: 'Bok Choy',
    category: 'leafy',
    price: 85,
    unit: '250g',
    image: 'https://picsum.photos/seed/bokchoy/400/300',
    description: 'Organic baby bok choy for stir-fries.',
    isOrganic: true,
    stock: 15,
    deliveryTime: '14 mins'
  },
  {
    id: '16',
    name: 'Asparagus Spears',
    category: 'exotics',
    price: 350,
    originalPrice: 420,
    unit: '250g',
    image: 'https://picsum.photos/seed/asparagus/400/300',
    description: 'Tender and nutritious organic asparagus.',
    isOrganic: true,
    stock: 10,
    deliveryTime: '16 mins'
  },
  {
    id: '17',
    name: 'Zucchini Green',
    category: 'vegetables',
    price: 65,
    unit: '500g',
    image: 'https://picsum.photos/seed/zucchini/400/300',
    description: 'Fresh organic green zucchini.',
    isOrganic: true,
    stock: 30,
    deliveryTime: '11 mins'
  },
  {
    id: '18',
    name: 'Thai Basil',
    category: 'leafy',
    price: 40,
    unit: '50g',
    image: 'https://picsum.photos/seed/basil/400/300',
    description: 'Fragrant organic Thai basil leaves.',
    isOrganic: true,
    stock: 25,
    deliveryTime: '12 mins'
  }
];
